SELECT
	TRANSACTION_ID
	,CONCAT('GB',c.CHECK_DIGITS,c.SWIFT_CODE,REPLACE(SORT_CODE,'-',''),t.ACCOUNT_NUMBER) AS IBAN
FROM PD2023_WK02_TRANSACTIONS AS t
JOIN PD2023_WK02_SWIFT_CODES AS c
ON t.BANK = c.BANK;